\set ON_ERROR_STOP on
\pset format unaligned
\pset tuples_only on
\pset pager off

\if :{?scale_factor}
\else
  \warn 'setup.sql requires -v scale_factor=<positive integer>'
  \quit 64
\endif

SELECT
    :scale_factor::bigint AS scale_factor,
    (:scale_factor::bigint * 10000)::bigint AS customer_count,
    (:scale_factor::bigint * 2000)::bigint AS product_count,
    (:scale_factor::bigint * 100000)::bigint AS history_count,
    (:scale_factor::bigint IN (1, 8, 32)) AS scale_factor_ok
\gset

\if :scale_factor_ok
\else
  \warn 'chapter 26 scale factor must be 1, 8, or 32'
  \quit 64
\endif

DO $guard$
BEGIN
    IF current_database() <> 'pg36_capacity' THEN
        RAISE EXCEPTION
            'chapter 26 setup requires pg36_capacity, got %',
            current_database();
    END IF;
    IF current_user <> 'dbuser_pg36bench' THEN
        RAISE EXCEPTION
            'chapter 26 setup requires dbuser_pg36bench, got %',
            current_user;
    END IF;
    IF pg_is_in_recovery() THEN
        RAISE EXCEPTION 'chapter 26 setup refuses a recovery node';
    END IF;
END
$guard$;

SET statement_timeout = 0;
SET lock_timeout = '5s';
SET synchronous_commit = on;

DROP SCHEMA IF EXISTS shopbench CASCADE;
CREATE SCHEMA shopbench AUTHORIZATION dbuser_pg36bench;

CREATE TABLE shopbench.fixture_marker (
    marker       text PRIMARY KEY,
    scale_factor bigint NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);

INSERT INTO shopbench.fixture_marker (marker, scale_factor)
VALUES ('pg36-ch26-disposable-capacity-fixture-v1', :scale_factor);

CREATE TABLE shopbench.customer (
    customer_id bigint PRIMARY KEY,
    segment     smallint NOT NULL,
    region      smallint NOT NULL,
    profile     text NOT NULL
);

CREATE TABLE shopbench.product (
    product_id  bigint PRIMARY KEY,
    category    smallint NOT NULL,
    price_cents integer NOT NULL CHECK (price_cents > 0),
    product_name text NOT NULL,
    description text NOT NULL
);

CREATE TABLE shopbench.inventory (
    product_id bigint PRIMARY KEY
        REFERENCES shopbench.product (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    quantity   integer NOT NULL CHECK (quantity >= 0),
    updated_at timestamptz NOT NULL
) WITH (fillfactor = 80);

CREATE TABLE shopbench.order_history (
    order_id    bigint PRIMARY KEY,
    customer_id bigint NOT NULL
        REFERENCES shopbench.customer (customer_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    product_id  bigint NOT NULL
        REFERENCES shopbench.product (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    quantity    smallint NOT NULL CHECK (quantity BETWEEN 1 AND 3),
    amount_cents integer NOT NULL CHECK (amount_cents > 0),
    status      text NOT NULL,
    placed_at   timestamptz NOT NULL,
    payload     text NOT NULL
);

CREATE INDEX order_history_customer_recent_idx
    ON shopbench.order_history (customer_id, order_id DESC)
    INCLUDE (product_id, quantity, amount_cents, status, placed_at);

CREATE TABLE shopbench.order_live (
    order_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  bigint NOT NULL
        REFERENCES shopbench.customer (customer_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    product_id   bigint NOT NULL
        REFERENCES shopbench.product (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    quantity     smallint NOT NULL CHECK (quantity BETWEEN 1 AND 3),
    amount_cents integer NOT NULL CHECK (amount_cents > 0),
    status       text NOT NULL,
    placed_at    timestamptz NOT NULL,
    request_ref  text NOT NULL UNIQUE
);

CREATE INDEX order_live_customer_recent_idx
    ON shopbench.order_live (customer_id, order_id DESC)
    INCLUDE (product_id, quantity, amount_cents, status, placed_at);

INSERT INTO shopbench.customer (
    customer_id,
    segment,
    region,
    profile
)
SELECT
    g,
    (g % 16)::smallint,
    (g % 64)::smallint,
    repeat(md5(g::text), 2)
FROM generate_series(1::bigint, :customer_count::bigint) AS g;

INSERT INTO shopbench.product (
    product_id,
    category,
    price_cents,
    product_name,
    description
)
SELECT
    g,
    (g % 128)::smallint,
    (500 + (g % 50000))::integer,
    'product-' || g,
    repeat(md5(('product-' || g)::text), 2)
FROM generate_series(1::bigint, :product_count::bigint) AS g;

INSERT INTO shopbench.inventory (product_id, quantity, updated_at)
SELECT
    product_id,
    (1000000 + product_id % 1000)::integer,
    timestamptz '2026-01-01 00:00:00+00'
FROM shopbench.product;

INSERT INTO shopbench.order_history (
    order_id,
    customer_id,
    product_id,
    quantity,
    amount_cents,
    status,
    placed_at,
    payload
)
SELECT
    g,
    ((g * 7919) % :customer_count) + 1,
    ((g * 1543) % :product_count) + 1,
    ((g % 3) + 1)::smallint,
    (
        (500 + (((g * 1543) % :product_count) + 1) % 50000)
        * ((g % 3) + 1)
    )::integer,
    CASE g % 20
        WHEN 0 THEN 'refunded'
        WHEN 1 THEN 'cancelled'
        ELSE 'fulfilled'
    END,
    timestamptz '2026-01-01 00:00:00+00'
        - ((g % 7776000)::double precision * interval '1 second'),
    repeat(md5(('order-' || g)::text), 2)
FROM generate_series(1::bigint, :history_count::bigint) AS g;

ANALYZE shopbench.customer;
ANALYZE shopbench.product;
ANALYZE shopbench.inventory;
ANALYZE shopbench.order_history;
ANALYZE shopbench.order_live;

SELECT jsonb_build_object(
    'scale_factor', :scale_factor::bigint,
    'customers', (SELECT count(*) FROM shopbench.customer),
    'products', (SELECT count(*) FROM shopbench.product),
    'historical_orders', (SELECT count(*) FROM shopbench.order_history),
    'database_bytes', pg_database_size(current_database()),
    'schema_bytes', (
        SELECT sum(pg_total_relation_size(c.oid))
        FROM pg_class AS c
        JOIN pg_namespace AS n
          ON n.oid = c.relnamespace
        WHERE n.nspname = 'shopbench'
          AND c.relkind IN ('r', 'p', 'm')
    )
) AS initialized;
